//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace onlineKredit.logic
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOnlineKredit : DbContext
    {
        public dbOnlineKredit()
            : base("name=dbOnlineKredit")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblArbeitgeber> tblArbeitgeber { get; set; }
        public DbSet<Beschaeftigungsart> AlleBeschaeftigungsarten { get; set; }
        public DbSet<Branche> AlleBranchen { get; set; }
        public DbSet<Einstellungen> AlleEinstellungen { get; set; }
        public DbSet<Familienstand> AlleFamiliaenstande { get; set; }
        public DbSet<FinanzielleSituation> AlleFinanzielleSituationen { get; set; }
        public DbSet<IdentifikationsArt> AlleIdentifikationsArten { get; set; }
        public DbSet<KontaktDaten> AlleKontaktDaten { get; set; }
        public DbSet<KontoDaten> AlleKontoDaten { get; set; }
        public DbSet<Kredit> AlleKredite { get; set; }
        public DbSet<tblKunde> tblKunde { get; set; }
        public DbSet<Land> AlleLaender { get; set; }
        public DbSet<Ort> AlleOrte { get; set; }
        public DbSet<Schulabschluss> AlleSchulabsluesse { get; set; }
        public DbSet<Titel> AlleTitel { get; set; }
        public DbSet<Wohnart> AlleWohnarten { get; set; }
    }
}
